### ISSUE TITLE
Month name

### ISSUE THREAD

**Issue by sebastianpisula** [RAAbbott/polaris-components#11]
I used your component but I don't see name of month

<img width="749" alt="image" src="https://github.com/RAAbbott/polaris-components/assets/15688144/26813079-0e65-44bb-9c40-a8bf646e60c9">

**Comment by RAAbbott** [comment]
Are you copy/pasting exactly how it is on the website? Month names are showing up just fine there

**Comment by sebastianpisula** [comment]
I forgot about.... locales 🤦‍♂️ Everything is okay.
