### ISSUE TITLE
Server-Client Style Mismatch Error in PricingCard Component

### ISSUE THREAD

**Issue by abdulrafaykhatri** [RAAbbott/polaris-components#13]
When rendering the `PricingCard` component, a warning is thrown due to a mismatch between the server-rendered and client-rendered styles. The server applies the following styles: `"width:18rem;border-radius:.75rem;position:relative;z-index:0"`, while the client applies `"width:18rem;box-shadow:;border-radius:.75rem;position:relative;z-index:0"`.

## Steps to Reproduce:
1. Render the `PricingCard` component within the application.
2. Observe the warning in the console indicating the mismatch between server and client styles.

## Expected Behavior:
The styles applied on both the server and client should match to avoid the warning and ensure consistent rendering.

## Actual Behavior:
There is a mismatch in the `box-shadow` property between the server and client.

## Environment:
- **Browser:** Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- **Framework:** Remix (using the Remix template from Shopify)
- **Node Version:** v22.6.0

## Possible Solution:
To resolve this issue, update the `boxShadow` property in the `PricingCard.jsx` component. Change:
```
boxShadow: featuredText ? "0px 0px 15px 4px #CDFEE1" : "",
```
to
```
boxShadow: featuredText ? "0px 0px 15px 4px #CDFEE1" : "none",
```

**Comment by RAAbbott** [comment]
Hey, thanks for bringing this up, will push out a fix today
