### ISSUE TITLE
Can we have granular components for some of the ones existing in the repo?

### ISSUE THREAD

**Issue by muchisx** [RAAbbott/polaris-components#14]
First of all, THANK YOU!

This is a gold mine, can't wait for open-source, I will contribute hugely!!

---

Here's what I mean, can we have stand-alone components for like these?

`ProgressCheckBox` ?
![image](https://github.com/user-attachments/assets/b7821297-a85b-4db0-b63d-05cf35dee1ac)

**Comment by RAAbbott** [comment]
Glad it's been helpful for you! I don't have any plans to break it down into more granular components like that, I think it's easy enough to copy the markup from the main component (the `SetupGuide` in this case) if you want just parts of a component. If it gets brought up enough though I will take another look
